### ISSUE TITLE
scbase collate --params /data proj1.loom error ValueError: Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by Hemantcnaik** [churchill-lab/scBASE#4]
* scBASE version:0.1.1
* Python version:3.6
* Operating System:linux

### Description

scbase collate --params /data proj1.loom  
while collating got the error 
### What I Did

```
Traceback (most recent call last):
  File "/opt/conda/envs/scbase/bin/scbase", line 11, in <module>
    load_entry_point('scbase==0.1.1', 'console_scripts', 'scbase')()
  File "/opt/conda/envs/scbase/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/scbase/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/scbase/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/scbase/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/scbase/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/scbase/lib/python3.6/site-packages/scbase-0.1.1-py3.6.egg/scbase/cli.py", line 150, in collate
    scbase.collate(indir, loomfile, tidfile, filetype, filename, model)
  File "/opt/conda/envs/scbase/lib/python3.6/site-packages/scbase-0.1.1-py3.6.egg/scbase/scbase.py", line 580, in collate
    for g_key, g_results in curdata_fh.items():
  File "/opt/conda/envs/scbase/lib/python3.6/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "/opt/conda/envs/scbase/lib/python3.6/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/opt/conda/envs/scbase/lib/python3.6/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

```

**Comment by jdwidawski** [comment]
Dear Hemantcnaik,

I am not a contributor of this package, however I have previously stumbled across the same issue while using this software.

Personally, I manually allowed pickle within the Anaconda environments' version of NumPy. 
Specifically, I edited these two following scripts:
- envs/scbase/lib/python3.6/site-packages/numpy/lib/npyio.py
- envs/scbase/lib/python3.6/site-packages/numpy/lib/format.py

In this case I would make sure that you are editing the NumPy scripts within the Anaconda environment directory (rather than the system-wide version), in order not to cause errors with other software that might also depend on NumPy.
